import Head from "next/head";
import styles from "@/styles/Home.module.css";
import UserFriendlyFeatures from "@/components/UserFriendlyFeatures";
import { Header } from "@/components/Header/header";
import { MultiTransactionSection } from "@/components/multi-transaction/multi-transaction";
import { HowItWorks } from "@/components/How-it-works";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <MultiTransactionSection />
        <HowItWorks />
        {/* <UserFriendlyFeatures /> */}
      </main>
    </>
  );
}
